name: Android Check CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java11
        uses: actions/setup-java@v2
        with:
            distribution: adopt
            java-version: 11

      - name: Build with Gradle
        run: ./gradlew build check
