name: Build and Deploy
on:
  release:
    types:
      - created

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and deploy
        run: ./gradlew clean build bintrayUpload  -PbintrayUser=${{secrets.JCENTER_NAME}}  -PbintrayKey=${{secrets.JCENTER_TOKEN}}  -PdryRun=false

      - name: Notification Slack
        uses: homoluctus/slatify@v2.1.2
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'Deployment Notification'
          mention: 'here'
          mention_if: 'failure'
          icon_emoji: ':rocket:'
          channel: '#android-apps-website'
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.CI_LIB_TOKEN }}